spring.application.name=server
spring.datasource.url=jdbc:mysql://localhost:3306/quantum_safe
spring.datasource.username=root
spring.datasource.password=madhu@mysql123
spring.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=madhumithavelusamy0@gmail.com
spring.mail.password=mwxxgajugluzzann
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
logging.level.org.springframework.mail=DEBUG
logging.level.org.eclipse.angus.mail=DEBUG